audeering/audinterface

audinterface/core/process.py, audinterface/core/segment.py
=> Use keyword argument with MultiIndex.set_levels()

CHANGELOG.rst
=> Release 0.8.1

audinterface/core/process.py, docs/usage.rst, tests/test_process.py
Relates to #54 
Adds option to use `Process` with a sliding window.
...
=> Process with sliding window

audinterface/core/feature.py, docs/usage.rst, tests/test_feature.py
=> Feature: add process_func_applies_sliding_window argument

CHANGELOG.rst
=> Release v0.9.0

CHANGELOG.rst
=> Release v0.9.1

CHANGELOG.rst
=> Release 0.9.2

audinterface/core/feature.py, docs/usage.rst, tests/test_feature.py
=> Use multi-column format for multi-channel Feature

CHANGELOG.rst
=> Release v0.10.0

CHANGELOG.rst
=> Release 0.10.2

audinterface/core/feature.py, audinterface/core/process.py, audinterface/core/process_with_context.py, audinterface/core/segment.py, audinterface/core/utils.py, docs/usage.rst
Switches to `emodb` v1.3.0 in the documentation examples.
=> DOC: use emodb 1.3.0

audinterface/core/process.py
Relates to #100 
Speeds up `Predict.process_*()` by avoiding calls to `pd.concat()` on a lot of small `pd.Series` objects. Instead, we now concatenate lists and create the final `pd.Series` from those.
```python
import time
import audb
import audinterface
db = audb.load(
'emodb',
version='1.3.0',
format='wav',
sampling_rate=16000,
mixdown=True,
)
def process_func(x, sr):
return [x.mean(), x.std()]
process = audinterface.Process(process_func=process_func)
t = time.time()
process.process_files(db.files)
print(time.time() - t)
```
* main branch: ~4.5 s
* this branch: ~0.3 s
=> Speed up Predict.process_*()

docs/requirements.txt
See https://github.com/audeering/audformat/pull/355
=> DOC: add ipykernel to requirements

docs/conf.py, docs/requirements.txt
Reade project name and authors from `pyproject.toml` file.
=> DOC: get project config from pyproject.toml

.github/workflows/doc.yml, .github/workflows/test.yml, tests/requirements.txt
Use dedicated GitHub Action to test building the documentation.
=> CI: use dedicated documentation Action

CHANGELOG.rst
=> Release 1.0.4

.github/workflows/publish.yml
Update CI pipeline to use 2FA for PyPI and fix parsing of changelog for Github release.
=> CI: fix publishing Action

LICENSE, pyproject.toml
Updates the list of authors and removes the upper year in the license file.
=> Update license year and authors

CHANGELOG.rst
I started working on #176, but it will take a few more days until that is finished.
hence, I propose to make another release in the mean time.
=> Release 1.2.2

CHANGELOG.rst
=> Release 1.2.3
