.github/workflows/publish.yml
Fixes #7 
`audinterface` needs `libsndfile` and `sox` for import.
Most probably we could also mock them during import, but I'm too lazy and just install them here for building the documentation.
=> CI: fix building docs for release

audinterface/core/process.py, audinterface/core/utils.py, tests/test_feature.py, tests/test_process.py
Use `unit='s'`  instead of `'sec'` when converting seconds with `pd.to_timedelta()`.
Reason: it seems that some (older?) versions of `pandas` do not support `'sec'`, see e.g. https://github.com/audeering/opensmile-python/issues/32#issuecomment-850786628
=> Fix unit in pd.to_timedelta()

audinterface/core/feature.py, audinterface/core/process.py, audinterface/core/segment.py, audinterface/core/utils.py, tests/test_feature.py, tests/test_process.py, tests/test_process_with_context.py, tests/test_segment.py
Closes #9 
Adds `root` argument to all functions that work on file input.
```python
db = audb.load(
'emodb',
version='1.1.1',
format='wav',
mixdown=True,
sampling_rate=16000,
full_path=False,
)
files = db.files[:10]
```
```
Index(['wav/03a01Fa.wav', 'wav/03a01Nc.wav', 'wav/03a01Wa.wav',
'wav/03a02Fc.wav', 'wav/03a02Nc.wav', 'wav/03a02Ta.wav',
'wav/03a02Wb.wav', 'wav/03a02Wc.wav', 'wav/03a04Ad.wav',
'wav/03a04Fd.wav'],
dtype='object', name='file')
```
```python
segment = audinterface.Segment(
process_func=lambda x, sr: pd.MultiIndex.from_arrays(
[
[pd.to_timedelta(0)],
[pd.to_timedelta(1, unit='s')],
],
names=['start', 'end'],
)
)
segment.process_index(files, root=db.root)
```
```
MultiIndex([('wav/03a01Fa.wav', '0 days', '0 days 00:00:01'),
('wav/03a01Nc.wav', '0 days', '0 days …
```
=> Add root argument

audinterface/core/feature.py
The docstring of `audinterface.Feature` was still listing `num_channels` as argument, but this is no longer an argument, but automatically calculated from `channels` and `mixdown`.
=> DOC: remove num_channels from Feature docstring

audinterface/core/feature.py, audinterface/core/process.py, audinterface/core/segment.py, audinterface/core/utils.py, audinterface/utils/__init__.py, docs/api-utils.rst, docs/conf.py, tests/test_feature.py, tests/test_process.py, tests/test_process_with_context.py, tests/test_segment.py, tests/test_utils.py
Closes #14 
Introduces utility function `audinterface.utils.signal_index()`, which creates a segmented index just like  `audformat.segmented_index()` but without the `file` level. It now takes care of using the correct `Timedelta` dtype.
The original example in #14 now fails:
```python
index = pd.MultiIndex.from_arrays(
[
[pd.to_timedelta(0)],
[pd.to_timedelta(pd.NaT)]
],
names=('start', 'end'),
)
process = audinterface.Process(keep_nat=True)
y = process.process_signal_from_index(np.zeros((1, 4)), 1, index)
y.index.get_level_values(1)
```
```
ValueError: Level 'end' must contain values of type 'timedelta64[ns]'.
```
and the fixed example has the correct type:
```python
index = pd.MultiIndex.from_arrays(
[
pd.to_timedelta([0]),
pd.to_timedelta([pd.NaT])
],
names=('start', 'end'),
)
process …
```
=> Add utils.signal_index()

audinterface/core/feature.py, audinterface/core/process.py, audinterface/core/segment.py, audinterface/core/utils.py, tests/test_feature.py, tests/test_utils.py
As discussed in https://github.com/audeering/audinterface/pull/18#discussion_r664273761 we now also forbid duplicates in indices that hold only `start` and `end` times.
```python
audinterface.utils.signal_index([0, 0], [1, 1])
```
```
Traceback (most recent call last):
File "/media/jwagner/Data/Git/pyaudinterface/my/my.py", line 25, in <module>
audinterface.utils.signal_index([0, 0], [1, 1])
File "/media/jwagner/Data/Git/pyaudinterface/audinterface/core/utils.py", line 258, in signal_index
assert_index(index)
File "/media/jwagner/Data/Git/pyaudinterface/audinterface/core/utils.py", line 31, in assert_index
'Found duplicates:\n'
ValueError: Found duplicates:
(Timedelta('0 days 00:00:00'), Timedelta('0 days 00:00:01'))
```
=> Forbid duplicates in signal index

audinterface/core/feature.py, audinterface/core/process.py, tests/test_feature.py
As discussed in #21 it would be nice to be less strict on the returned shape of the process function that can be used with `Feature`. Especially since we already support 2d, but in that case the first dimension always has to be the channels, which does not always make sense, e.g. with `process_func_is_mono=True` we already know that the channel dimension will be 1.
Luckily, since `channels` and `features` are fixed and only `frames` can vary, we can derive the correct 3d shape from 1 or 2 dimensions. In this PR we add support for:
* `(features)`
* `(features, frames)`
in addition to:
* `(channels, features)`
* `(channels, features, frames)`
While implementing this PR I realized that `__call__()` did not return `(channels, features, frames)` as promised, but the original shape from the …
=> Support more feature shapes

audinterface/core/feature.py, tests/test_feature.py
Closes #21
Add support for to scalars and lists to `Feature`.
```python
feature = audinterface.Feature(
['x'],
process_func=lambda x, sr: 1,
)
feature.process_file('mono.wav')
```
```
x
file     start  end                         
mono.wav 0 days 0 days 00:00:07.247709751  1
```
```python
feature = audinterface.Feature(
['x', 'y'],
process_func=lambda x, sr: [1, 2],
)
feature.process_file('mono.wav')
```
```
x  y
file     start  end                            
mono.wav 0 days 0 days 00:00:07.247709751  1  2
```
```pythonfeature = audinterface.Feature(
['x', 'y'],
process_func=lambda x, sr: [[1, 1, 1], [2, 2, 2]],
win_dur=1.0,
)
feature.process_file('mono.wav')
```
```
x  y
file     start                  end                         
mono.wav 0 days 00:00:00        0 days 00:00:01 …
```
=> Feature: support scalars and lists

audinterface/core/feature.py
=> DOC: fix typo in Feature docstring

audinterface/core/feature.py, audinterface/core/process.py
This adjusts the code to avoid the following warnings
as can be seen in https://github.com/audeering/audinterface/runs/4699571292?check_suite_focus=true
=> Avoid pandas warnings

CHANGELOG.rst
Before doing a 1.0.0 release we need to do a 0.8.0 release in between as we have marked stuff as deprecated and to be removed with 1.0.0 (https://github.com/audeering/audinterface/pull/28), and we have removed stuff that was marked to be removed in 0.8.0 (https://github.com/audeering/audinterface/pull/29).
=> Release 0.8.0

audinterface/core/feature.py, audinterface/core/process.py, audinterface/core/segment.py, tests/test_feature.py, tests/test_process.py, tests/test_process_with_context.py, tests/test_segment.py
Closes #35 
If a folder is empty or does not exist, `process_folder()` currently raises a `ValueError: All objects passed were None`.
This changes the behavior of `process_folder()` to:
* Raise `FileNotFoundError` if folder does not exist. 
* Return an empty series/frame if folder is empty.
Other change: when an empty series or frame is returned, the data type is set to `object`.
=> Process_folder(): handle empty and non-existing folder

audinterface/core/feature.py, tests/test_feature.py
If a single string is passed to `Feature' it will be automatically converted to an array.
=> Feature: support plain string for single feature

setup.cfg, tests/test_feature.py, tests/test_process.py, tests/test_process_with_context.py
Closes #37 
I added an additional test that checks that the datatype of features stays the same as the datatype of the signal, when the feature extraction function that is used is independent of the datatype (e.g. does not convert everything to `int`).
In addition, I had to fix two tests that were using `audresample.resample()` with float64 signals as inputs.
=> Depend on audresample>=1.1.0

docs/conf.py
This fixes the link to the `numpy` API documentation, compare https://github.com/audeering/audinterface/runs/5091818430?check_suite_focus=true
=> DOC: fix numpy intershpinx link

docs/conf.py, docs/index.rst, docs/requirements.txt, docs/usage.rst
Closes #5.
This adds a first basic usage section to the documentation, covering:
* using `audinterface.Process`
* using `audinterface.Feature`
* building a feature extraction object with `audinterface.Feature` and `audobject.Object`
Building the documentation will fail as I get the following warning due to storing and loading the feature extraction object:
```
WARNING: Cell printed to stderr:
/home/audeering.local/hwierstorf/.envs/audinterface/lib/python3.8/site-packages/audobject/core/utils.py:51: RuntimeWarning: Could not determine a version for module '__main__'.
warnings.warn(
```
Any idea how to avoid this?
=> DOC: add usage section

audinterface/__init__.py, audinterface/core/feature.py, audinterface/core/process.py, audinterface/core/segment.py, audinterface/core/utils.py, docs/conf.py, tests/requirements.txt
Closes #11 
This adds examples to all API functions and classes.
In addition, it removes the example from `__init__.py` as we now have the same in the docstrings.
=> DOC: add docstring examples

.github/workflows/test.yml, README.rst
This extends the README to a similar level we have for other packages:
=> DOC: extend README

audinterface/core/process.py, tests/test_process_with_context.py
Closes #47 
Alternative implementation to https://github.com/audeering/audinterface/pull/49
This raises an error if the length of the returned sequence of the process function does not match the number of segments for `audinterafce.ProcessWithContext`.
=> ProcessWithContext requires output per segment

audinterface/core/feature.py, audinterface/core/process.py, audinterface/core/segment.py, audinterface/core/utils.py, tests/test_feature.py
As proposed in https://github.com/audeering/audinterface/pull/52#issuecomment-1164249905 this uses the same time format for `start`, `end`, `win_dur`, `hop_dur` and allows specifying of samples with a string, e.g. `'44100'`.
The `unit` argument of `audinterafce.Feature` was deprecated as it is no longer needed.
=> Deprecate unit, specify samples as string

audinterface/core/feature.py, audinterface/core/process.py, audinterface/core/segment.py, tests/test_process.py
Closes #41 
This adds the arguments `min_signal_dur` and `max_signal_dur` to `audinterface.Process`, `audinterface.Feature`, and `audinterface.Segment`, but not to `audinterafce.ProcessWithContext` as there the process function should take care itself about it.
The signal is cut at the end or zero padded at the end to fullfill the requested requirements.
If both arguments are given it is not checked if `max_signal_dur` > `min_signal_dur`, but `max_signal_dur` is always applied first.
=> Add min_signal_dur, max_signal_dur arguments

audinterface/core/feature.py, audinterface/core/process.py, audinterface/core/segment.py, audinterface/core/utils.py, audinterface/utils/__init__.py, docs/api-utils.rst, tests/test_feature.py
Closes #59 
~~I also adjusted the return type from `typing.Sequence[pd.Timedelta]` to `pd.TimedeltaIndex`.
I'm also fine with changing the output of the function to the return type we mentioned before, but I'm not sure if this will break the behavior inside `audinterface`.~~
---
I updated related docstrings to link now to this new utility function:
=> Add audinterface.utils.to_timedelta()

docs/usage.rst
This ensures that the HTML output of `df`, `y`, `index` in the usage section are independent of the root path of the underlying data.
In addition, the index presentation is fixed to look the same as for dataframe or series.
Example:
=> DOC: better HTML representations of tables

.github/workflows/test.yml, audinterface/core/segment.py, setup.cfg, tests/requirements.txt
This pull requests solves two issues to get the tests working again:
It makes sure to use `audformat.segmented_index()` instead of `pd.MultiIndex` and `audformat.utils.union()` instead of `index.union()` whenever dealing with segemented indices to make sure we get the correct dtype of the `file` level. It uses now only `audformat` functions to make sure it will still work even if we change the behavior of `audformat.sefgmented_index()` again.
As `audformat>=0.15` does only work with Python 3.8, I removed support for Python 3.7 as well.
Seems like they don't want to solve https://github.com/tholo/pytest-flake8/issues/87, but propose instead of doing syntax/style checks as `pre-commit`. If I understand this correctly it would run `flake8` locally before doing the commit.
The disadvantage …
=> Require audformat>=0.15.3 and flake8<5.0.0

audinterface/core/utils.py
Changes
to
It seems using `signal: ` before had the consequence that this was used as return type and even affected the order in which "Return type" and "Returns" are presented. 
The order shown for the changes here is in line with the other docstrings.
=> DOC: fix return values of utils.read_audio()

setup.cfg, tests/requirements.txt, tests/test_process.py
Closes #68 
This closes the issue by adding a test for `audobject` to identify possible issues earlier.
The actual issue was resolved in `audobject`: in https://github.com/audeering/audobject/pull/49
=> TST: test for audobject

docs/usage.rst
Before we were passing the mono signal to the first example showing that the first channel is used.
Fixed now:
=> DOC: fix typo in multi-channel usage example

.github/workflows/flake8.yml, .pre-commit-config.yaml, CONTRIBUTING.rst, setup.cfg, tests/requirements.txt
This uses [pre-commit](https://pre-commit.com) instead of `pytest` to execute the `flake8` tests.
It also fixes a few flake8 issues and adds a coding convention section to CONTRIBUTING.
=> TST: use pre-commit for flake8 checks

CHANGELOG.rst
As we now have a new release of `audformat` with the new API doc URLs we can create a new `audinterface` release as well as this might create links to the `audformat` API documentation.
=> Release 0.10.1

audinterface/core/feature.py, audinterface/core/process.py, tests/test_feature.py, tests/test_process.py
Closes #71 
This adds the argument `preserve_index` to `Process.process_index()` and `Feature.process_index()`. If `True` it will return a filewise index instead of a segmented index if provided with a filewise index. This has the advantage that one can directly assign the result to a dataframe with the original index as outlined in #71.
It's not implemented in the most elegant way as nearly all internal private functions and the caching requires segmented index. If `preserve_index=True` the index is first converted to a segmented index anyway and also the results are always cached as a segmented index. We just convert the index back to a segmented index before returning it to the user.
=> Add preserve_index argument to process_index()

.github/workflows/test.yml, README.rst
As we use `emodb` loaded by `audb` in the documentation examples, it will make sense to cache the data as we do in https://github.com/audeering/audb to avoid reloading the data with every pipeline from the external server.
=> CI: cache emodb database

audinterface/core/process.py, audinterface/core/utils.py, docs/conf.py, setup.cfg, tests/test_utils.py
This updates `audinterface.utils.to_timedelta()` to use `audmath.duration_in_seconds()` as single source of truth for conversion to seconds.
The behavior of `audinterface.utils.to_timedelta()` is not changed as we have only a single `sampling_rate` argument for a whole list of duration values:
* float and integer values will always be tyreated as representing duration in seconds
* only string values without a unit are expected to represent samples, and we raise an error if such a value is given, but no `sampling_rate` value
=> Use audmath in audinterface.utils.to_timedelta()

audinterface/core/feature.py, tests/test_feature.py
Relates to #100 
Speeds up `Feature.process_*()` by avoiding calls to `pd.concat()` on a lot of small `pd.DataFrame` objects. Instead, we now concatenate lists / numpy arrays and create the final `pd.DataFrame` from those.
```python
import time
import audb
import audinterface
db = audb.load(
'emodb',
version='1.3.0',
format='wav',
sampling_rate=16000,
mixdown=True,
)
def process_func(x, sr):
return [x.mean(), x.std()]
feature = audinterface.Feature(
['mean', 'std'],
process_func=process_func,
)
t = time.time()
feature.process_files(db.files)
print(time.time() - t)
```
* main branch: ~8.5 s
* this branch: ~4.5 s
=> Speed up Feature.process_*()

audinterface/core/process_with_context.py, tests/test_process_with_context.py
Relates to #100 
Speeds up `PredictWithContext.process_*()` by avoiding calls to `pd.concat()` on a lot of small `pd.Series` objects. Instead, we now concatenate lists and create the final `pd.Series` from those.
```python
import time
import audb
import audinterface
db = audb.load(
'emodb',
version='1.3.0',
format='wav',
sampling_rate=16000,
mixdown=True,
)
def process_func(x, sr, starts, ends):
y = []
for start, end in zip(starts, ends):
y.append(x[:, start:end].mean())
return y
process = audinterface.ProcessWithContext(process_func=process_func)
t = time.time()
process.process_index(db.files)
print(time.time() - t)
```
* main branch: ~4.0 s
* this branch: ~0.6 s
=> Speed up ProcessWithContext.process_*()

audinterface/core/segment.py
Closes #106 
Avoids calling `audformat.utils.union()` by collecting files, starts and ends in a list and use them to directly create the final index.
=> Speed up Segment.process_*()

audinterface/core/feature.py, audinterface/core/process.py, audinterface/core/process_with_context.py, audinterface/core/segment.py, audinterface/core/utils.py, tests/test_feature.py, tests/test_process.py, tests/test_process_with_context.py, tests/test_segment.py
When introducing `process_func_args` in version 0.8.0 beginning of the year we stated that it will be removed in version 1.0.0.
As I think we should release the new version as 1.0.0, this removes it.
=> Remove deprecated kwargs for process_func_args

audinterface/core/feature.py, tests/test_feature.py
=> Fix: do not truncate string features

setup.cfg, tests/test_process.py
Closes #113 
This adds a test for #113 which fails with `audformat==1.0.0` and updates the dependency to `audformat>=1.0.1` to incorporate https://github.com/audeering/audformat/pull/380 which fixes the issue described in #113.
=> Require audformat>=1.0.1

.github/workflows/publish.yml
We updated to use `pyproject.toml` in https://github.com/audeering/audinterface/pull/125, but forgot to update the `publish` Action accordingly.
=> CI: update publish Action to pyproject.toml

audinterface/core/utils.py, pyproject.toml, tests/test_process.py, tests/test_utils.py
Closes #123 
For certain values of `start` and `end` `process_file(..., start=start, end=end)` returned a different result than `process_signal(..., start=start, end=end)` as the duration values were rounded differently inside `audinterface.utils.read_audio()`, which is used in `process_file()`.
The behavior is now fixed inside ` audinterface.utils.read_signal()` and `process_file()` returns now the same results as `process_signal()`.
The fix uses `audmath.samples()` as a ground truth for converting to samples and relies on the fix of `audiofile` to also use `audmath.samples()` as ground truth (https://github.com/audeering/audiofile/pull/124).
Beside the fix, this pull request also adds two tests that fail for the current implementation in `main`.
=> Fix rounding of start/end in utils.read_signal()

.github/workflows/doc.yml, README.rst
Re-enable checking for links and fix link to installation section in README.
=> CI: re-enable linkcheck and fix link

.github/workflows/publish.yml
Ensures the release name on github is presented as "Release vX.Y.Z"
=> CI: fix release name on GitHub

audinterface/core/segment.py, tests/test_process.py
Closes #135 
In `audinterace.Segment` the process functions return an index, which in most cases is generated at the end of the involved process function. Usually, this involves requesting `starts` and `ends` values from previous processing steps. In some cases these were wrongly done by `index.levels` instead of `index.get_level_values()`.
This expands the tests and fixes the underlying issue.
=> Fix order of start/end values in audinterface.Segment

audinterface/core/utils.py, tests/test_utils.py
Closes #134 
~~Blocked by #135~~
When providing the time already as `pd.Timedelta` we have to ensure that we do not loose precision (compare https://github.com/audeering/audinterface/issues/113). The easiest way to achieve this is to check if the type is already `pd.Timedelta` and not convert in that case.
=> Fix precision of audinterface.utils.to_timedelta()

audinterface/core/process.py, tests/test_process.py
Closes #138 
Ensures the `segment` object is not ignored when calling `audinterface.Process.process_files()`.
=> Fix Process.process_files() with segment object

tests/test_process.py
Closes #139 
With https://github.com/audeering/audinterface/pull/141 we also fixed #139 and `process_folder()` now returns an empty index, if the underlying `segment` object returns an empty index:
```python
>>> process.process_folder('.').index
MultiIndex([], names=['file', 'start', 'end'])
```
In this merge request we just enable a test that was failing before #141 was merged.
=> TST: test process_folder() for empty segment index

audinterface/core/feature.py, audinterface/core/process.py, audinterface/core/segment.py, tests/test_feature.py, tests/test_process.py
Closes #140
This adds the `include_root` argument to
* `audinterface.Process.process_folder()`
* `audinterface.Segment.process_folder()`
* `audinterface.Feature.process_folder()`
If set to `False` it will return the relative path in the resulting index.
=> Add include_root argument to process_folder()

audinterface/core/process.py, tests/conftest.py, tests/test_process.py
This is related to https://github.com/audeering/audinterface/issues/134, but has a different cause as the reason we loose precision is not related to calling `to_timedelta()` but due to reading in only a part of the file inside `process_file()` if `start` and `end` are given. The values are then of cause rounded to the nearest sample and we have to save the difference to the original requested values in order to restore the correct values.
---
To reduce the number of times we have to write an audio file, this introduces also an `audio` test fixture, that writes the audio files only once.
=> Fix precision of end values in process_file()

audinterface/core/feature.py, tests/test_feature.py
Extends the tests for the process functions of `audinterface.Process` when `segment` object is present to `audinterface.Feature`.
In order to pass the tests the following behavior have changed:
if a `segment` object is present that returns an empty index, `audinterface.Feature.process_*()` no longer returns `Index([], dtype='object')`, but `MultiIndex([], names=['file', 'start', 'end'])`.
=> TST: add tests for segment in argument of Feature

audinterface/__init__.py
`pkg_resources` is deprecated and since Python 3.8 we can use `importlib.metadata` to get the version of a package.
=> Use importlib.metadata instead of pkg_resources

docs/requirements.txt, tests/test_process.py
Closes #152 
Add `pyarrow` as dependency as this is needed in `pandas` 3.0.0, see https://github.com/pandas-dev/pandas/issues/54466.
It also fixes an error in the `process_signal()` tests which did not account for returning always a signal of at least 2 dimensions when using `None` as process function. The behavior of this did not change, but the underlying test function (`pd.testing.assert_series_equal()`) is raising an error if the shapes to not match with `pandas>=2.2.0`
=> DOC: require pyarrow

audinterface/core/feature.py, audinterface/core/process.py, audinterface/core/segment.py, audinterface/core/utils.py, pyproject.toml, tests/requirements.txt, tests/test_feature.py, tests/test_process.py
This tests the code for `audeer>=2.0.0` and updates the code.
It turns out that there are no needed changes for `audeer>=2.0.0` and we can instead update to `audeer>=1.18.0` and `audeer>=1.21.0` for the tests.
=> Depend on audeer>=1.18.0

docs/usage.rst
Updates a usage example in the documentation to avoid `pandas` deprecation warnings.
=> DOC: avoid deprecation warnings

.github/workflows/doc.yml, .github/workflows/publish.yml
Use Python 3.10 when testing building the docs and when publishing the Python package and Github pages.
=> CI: use Python 3.10 for docs and publish Actions

audinterface/core/feature.py, audinterface/core/process.py, audinterface/core/process_with_context.py, audinterface/core/segment.py, tests/test_process_func_args.py
Closes #156 
This adds a `process_func_args` argument to all the processing methods, e.g. `audinterface.Process.process_index()`.
It can be used to overwrite the `process_func_args` argument used during instantiation of the interface.
Example:
```python
import audinterface
import numpy as np
def addition(signal, sampling_rate, value=1):
return signal + value * signal
interface = audinterface.Process(
process_func=addition,
process_func_args={"value": 2},
)
signal = np.ones((1, 3))
sampling_rate = 8000
interface.process_signal(signal, sampling_rate, process_func_args={"value": 3})
```
returns
```
start   end                   
0 days  0 days 00:00:00.000375    [[4.0, 4.0, 4.0]]
dtype: object
```
It will not overwrite the content of the class attribute `interface.process_func_args`, which …
=> Add per execution process_func_args argument

audinterface/core/feature.py, tests/test_feature.py
As mentioned in #164, the `process_func_applies_sliding_window` should have been changed from `True` to `False` with version 1.2.0 of `audinterface`.
=> Set process_func_applies_sliding_window=False

audinterface/core/feature.py, tests/test_feature.py
Closes #164
Removes the handling of deprecated `unit` argum,ent in `audinterface.Feature` as it was marked to be removed in v1.2.0.
=> Remove deprecated unit argument from Feature

audinterface/core/feature.py, audinterface/core/process.py, audinterface/core/process_with_context.py, audinterface/core/segment.py, tests/test_feature.py, tests/test_process.py, tests/test_process_with_context.py, tests/test_segment.py
Closes #165 
Ensure, that the `multiprocessing` argument of `audinterface.Process`, `audinterface.Feature`, `audinterface.Segment` does not result in an pickle related error, if set to `True`. Multiprocessing relies on [pickling all involved objects](https://laszukdawid.com/blog/2017/12/13/multiprocessing-in-python-all-about-pickling/) to communicate between processes.
The error was originally reported in https://github.com/audeering/opensmile-python/issues/104.
I added tests for `audinterface.Process`, `audinterface.Feature`, `audinterface.Segment`, to detect the error.
Most tests included already the `multiprocessing` argument, but it was always set to `False`.
The reason for the error consisted of two parts:
1. In https://github.com/audeering/audinterface/pull/157 we introduced …
=> Fix multiprocessing for Process, Feature, Segment

audinterface/core/segment.py, docs/usage.rst, tests/test_segment.py
New method `Segment.process_table()`.
Added Usage instructions in `Usage.rst` and tests.
https://github.com/audeering/audinterface/issues/167#issuecomment-2082435678
From usage documentation:
=> Add audinterface.Segment.process_table()

.github/workflows/test.yml, audinterface/core/process.py, docs/requirements.txt, pyproject.toml
This requires the latest version of `audmath` to ensure, that `audinterface` also works with `numpy` 2.0.
We also have to require `numpy<2.0.0` when building the docs as we use `librosa` in an example, which fails due to https://github.com/dofuuz/python-soxr/issues/28.
We cannot easily test Python 3.8 as `audb` caches created with `numpy` 2 cannot be read with older versions of `numpy`. As Python 3.8 reaches anyway its end of life, I decided to remove already support for Python 3.8, instead of adding workarounds for the tests.
=> Require audmath>=1.4.1 to support numpy 2.0

audinterface/conftest.py, docs/conf.py, docs/conftest.py, docs/requirements.txt, docs/usage.rst, pyproject.toml, tests/requirements.txt
So far we used the following setup for ensuring the expected code output in the documentation:
* Use the [doctest-plus](https://github.com/scientific-python/pytest-doctestplus) pytest plugin for testing the docstring examples
* Use the [jupyter-sphinx](https://github.com/jupyter/jupyter-sphinx) sphinx extension for running any code blocks in the usage documentation and presenting its output
The disadvantage of [jupyter-sphinx](https://github.com/jupyter/jupyter-sphinx) is that it requires a lot of dependencies, and we cannot control if the output of the code looks as expected. We can only test if the code runs without any error. In addition, we cannot directly use `ELLIPSIS` to change parts of the output, e.g. to hide absolute paths or strings that are too long, but needed to write extra …
=> TST: use sybil for doctests
